/**
 * Venus Inference Engine - Embedded OpenCL Kernels
 * 
 * All kernels are embedded as C strings for single-file deployment.
 * Compile-time defines are used for tuning:
 *   TILE_M, TILE_N, TILE_K - GEMM tile sizes
 *   WG_SIZE_X, WG_SIZE_Y - Work group sizes
 *   VEC_WIDTH - Vector width for vectorized ops
 *   USE_LOCAL_MEM - Whether to use local memory
 *   LOCAL_MEM_PAD - Padding for bank conflict avoidance
 *   ATTENTION_BLOCK - Block size for attention
 *   REDUCTION_BLOCK - Block size for reductions
 *   DEQUANT_BLOCK - Block size for dequantization
 * 
 * Copyright (c) 2024 EdgeFlow AI
 * Licensed under Apache 2.0
 */

#ifndef OPENCL_KERNELS_H
#define OPENCL_KERNELS_H

static const char* OPENCL_KERNELS_SOURCE = 
// ============================================================================
// Configuration and Helper Macros
// ============================================================================
"#ifndef TILE_M\n"
"#define TILE_M 8\n"
"#endif\n"
"#ifndef TILE_N\n"
"#define TILE_N 8\n"
"#endif\n"
"#ifndef TILE_K\n"
"#define TILE_K 8\n"
"#endif\n"
"#ifndef WG_SIZE_X\n"
"#define WG_SIZE_X 8\n"
"#endif\n"
"#ifndef WG_SIZE_Y\n"
"#define WG_SIZE_Y 8\n"
"#endif\n"
"#ifndef VEC_WIDTH\n"
"#define VEC_WIDTH 4\n"
"#endif\n"
"#ifndef USE_LOCAL_MEM\n"
"#define USE_LOCAL_MEM 1\n"
"#endif\n"
"#ifndef LOCAL_MEM_PAD\n"
"#define LOCAL_MEM_PAD 1\n"
"#endif\n"
"#ifndef ATTENTION_BLOCK\n"
"#define ATTENTION_BLOCK 64\n"
"#endif\n"
"#ifndef REDUCTION_BLOCK\n"
"#define REDUCTION_BLOCK 256\n"
"#endif\n"
"#ifndef DEQUANT_BLOCK\n"
"#define DEQUANT_BLOCK 32\n"
"#endif\n"
"\n"

// ============================================================================
// GEMM Kernels
// ============================================================================
"// Tiled GEMM: C = alpha * A @ B + beta * C\n"
"__kernel void gemm_f32(\n"
"    __global const float* A,\n"
"    __global const float* B,\n"
"    __global float* C,\n"
"    const int M,\n"
"    const int N,\n"
"    const int K,\n"
"    const float alpha,\n"
"    const float beta\n"
") {\n"
"    const int row = get_global_id(0);\n"
"    const int col = get_global_id(1);\n"
"    \n"
"    if (row >= M || col >= N) return;\n"
"    \n"
"    float sum = 0.0f;\n"
"    \n"
"#if USE_LOCAL_MEM\n"
"    __local float tileA[TILE_M][TILE_K + LOCAL_MEM_PAD];\n"
"    __local float tileB[TILE_K][TILE_N + LOCAL_MEM_PAD];\n"
"    \n"
"    const int localRow = get_local_id(0);\n"
"    const int localCol = get_local_id(1);\n"
"    const int tileRow = get_group_id(0) * TILE_M;\n"
"    const int tileCol = get_group_id(1) * TILE_N;\n"
"    \n"
"    for (int t = 0; t < (K + TILE_K - 1) / TILE_K; t++) {\n"
"        // Load tiles\n"
"        int aRow = tileRow + localRow;\n"
"        int aCol = t * TILE_K + localCol;\n"
"        int bRow = t * TILE_K + localRow;\n"
"        int bCol = tileCol + localCol;\n"
"        \n"
"        if (aRow < M && aCol < K)\n"
"            tileA[localRow][localCol] = A[aRow * K + aCol];\n"
"        else\n"
"            tileA[localRow][localCol] = 0.0f;\n"
"        \n"
"        if (bRow < K && bCol < N)\n"
"            tileB[localRow][localCol] = B[bRow * N + bCol];\n"
"        else\n"
"            tileB[localRow][localCol] = 0.0f;\n"
"        \n"
"        barrier(CLK_LOCAL_MEM_FENCE);\n"
"        \n"
"        // Compute partial dot product\n"
"        for (int k = 0; k < TILE_K; k++) {\n"
"            sum += tileA[localRow][k] * tileB[k][localCol];\n"
"        }\n"
"        \n"
"        barrier(CLK_LOCAL_MEM_FENCE);\n"
"    }\n"
"#else\n"
"    // Simple non-tiled version for CPU\n"
"    for (int k = 0; k < K; k++) {\n"
"        sum += A[row * K + k] * B[k * N + col];\n"
"    }\n"
"#endif\n"
"    \n"
"    // Apply alpha/beta scaling\n"
"    if (beta != 0.0f) {\n"
"        C[row * N + col] = alpha * sum + beta * C[row * N + col];\n"
"    } else {\n"
"        C[row * N + col] = alpha * sum;\n"
"    }\n"
"}\n"
"\n"

// Quantized GEMM with Q8_0
"// GEMM with Q8 quantized B matrix (dequantize on-the-fly)\n"
"__kernel void gemm_q8(\n"
"    __global const float* A,\n"
"    __global const char* B_q8,\n"
"    __global const float* scales,\n"
"    __global float* C,\n"
"    const int M,\n"
"    const int N,\n"
"    const int K\n"
") {\n"
"    const int row = get_global_id(0);\n"
"    const int col = get_global_id(1);\n"
"    \n"
"    if (row >= M || col >= N) return;\n"
"    \n"
"    float sum = 0.0f;\n"
"    \n"
"    // Process in blocks of 32 (Q8_0 block size)\n"
"    for (int k = 0; k < K; k += DEQUANT_BLOCK) {\n"
"        int block_idx = (col * K + k) / DEQUANT_BLOCK;\n"
"        float scale = scales[block_idx];\n"
"        \n"
"        for (int i = 0; i < DEQUANT_BLOCK && (k + i) < K; i++) {\n"
"            float a_val = A[row * K + k + i];\n"
"            float b_val = (float)B_q8[col * K + k + i] * scale;\n"
"            sum += a_val * b_val;\n"
"        }\n"
"    }\n"
"    \n"
"    C[row * N + col] = sum;\n"
"}\n"
"\n"

// Quantized GEMM with Q4_0
"// GEMM with Q4 quantized B matrix (packed 2 values per byte)\n"
"__kernel void gemm_q4(\n"
"    __global const float* A,\n"
"    __global const uchar* B_q4,\n"
"    __global const float* scales,\n"
"    __global float* C,\n"
"    const int M,\n"
"    const int N,\n"
"    const int K\n"
") {\n"
"    const int row = get_global_id(0);\n"
"    const int col = get_global_id(1);\n"
"    \n"
"    if (row >= M || col >= N) return;\n"
"    \n"
"    float sum = 0.0f;\n"
"    \n"
"    // Process in blocks of 32 (Q4_0 block size)\n"
"    for (int k = 0; k < K; k += DEQUANT_BLOCK) {\n"
"        int block_idx = (col * K + k) / DEQUANT_BLOCK;\n"
"        float scale = scales[block_idx];\n"
"        \n"
"        for (int i = 0; i < DEQUANT_BLOCK && (k + i) < K; i += 2) {\n"
"            int byte_idx = (col * K + k + i) / 2;\n"
"            uchar packed = B_q4[byte_idx];\n"
"            \n"
"            // Unpack two 4-bit values\n"
"            int v0 = (int)(packed & 0x0F) - 8;\n"
"            int v1 = (int)(packed >> 4) - 8;\n"
"            \n"
"            float a0 = A[row * K + k + i];\n"
"            float a1 = (k + i + 1 < K) ? A[row * K + k + i + 1] : 0.0f;\n"
"            \n"
"            sum += a0 * (float)v0 * scale;\n"
"            sum += a1 * (float)v1 * scale;\n"
"        }\n"
"    }\n"
"    \n"
"    C[row * N + col] = sum;\n"
"}\n"
"\n"

// ============================================================================
// Attention Kernels
// ============================================================================
"// Compute attention scores: scores = Q @ K^T * scale\n"
"__kernel void attention_scores(\n"
"    __global const float* Q,\n"
"    __global const float* K,\n"
"    __global float* scores,\n"
"    const int batch,\n"
"    const int heads,\n"
"    const int seq_len,\n"
"    const int kv_len,\n"
"    const int head_dim,\n"
"    const float scale\n"
") {\n"
"    const int q_pos = get_global_id(0);\n"
"    const int k_pos = get_global_id(1);\n"
"    const int bh = get_global_id(2);  // batch * heads\n"
"    \n"
"    if (q_pos >= seq_len || k_pos >= kv_len) return;\n"
"    \n"
"    const int b = bh / heads;\n"
"    const int h = bh % heads;\n"
"    \n"
"    // Compute dot product\n"
"    float dot = 0.0f;\n"
"    int q_offset = ((b * heads + h) * seq_len + q_pos) * head_dim;\n"
"    int k_offset = ((b * heads + h) * kv_len + k_pos) * head_dim;\n"
"    \n"
"    for (int d = 0; d < head_dim; d++) {\n"
"        dot += Q[q_offset + d] * K[k_offset + d];\n"
"    }\n"
"    \n"
"    // Store scaled score\n"
"    int score_idx = ((b * heads + h) * seq_len + q_pos) * kv_len + k_pos;\n"
"    scores[score_idx] = dot * scale;\n"
"}\n"
"\n"

"// Apply causal mask and softmax to attention scores\n"
"__kernel void attention_softmax(\n"
"    __global float* scores,\n"
"    const int batch,\n"
"    const int heads,\n"
"    const int seq_len,\n"
"    const int kv_len,\n"
"    const int causal\n"
") {\n"
"    const int q_pos = get_global_id(0);\n"
"    const int bh = get_global_id(1);\n"
"    \n"
"    if (q_pos >= seq_len) return;\n"
"    \n"
"    int base_idx = (bh * seq_len + q_pos) * kv_len;\n"
"    \n"
"    // Find max for numerical stability\n"
"    float max_val = -INFINITY;\n"
"    for (int k = 0; k < kv_len; k++) {\n"
"        if (causal && k > q_pos) {\n"
"            scores[base_idx + k] = -INFINITY;\n"
"        } else {\n"
"            max_val = fmax(max_val, scores[base_idx + k]);\n"
"        }\n"
"    }\n"
"    \n"
"    // Compute exp and sum\n"
"    float sum = 0.0f;\n"
"    for (int k = 0; k < kv_len; k++) {\n"
"        if (!causal || k <= q_pos) {\n"
"            float val = exp(scores[base_idx + k] - max_val);\n"
"            scores[base_idx + k] = val;\n"
"            sum += val;\n"
"        }\n"
"    }\n"
"    \n"
"    // Normalize\n"
"    float inv_sum = 1.0f / (sum + 1e-9f);\n"
"    for (int k = 0; k < kv_len; k++) {\n"
"        if (causal && k > q_pos) {\n"
"            scores[base_idx + k] = 0.0f;\n"
"        } else {\n"
"            scores[base_idx + k] *= inv_sum;\n"
"        }\n"
"    }\n"
"}\n"
"\n"

"// Compute attention output: output = scores @ V\n"
"__kernel void attention_output(\n"
"    __global const float* scores,\n"
"    __global const float* V,\n"
"    __global float* output,\n"
"    const int batch,\n"
"    const int heads,\n"
"    const int seq_len,\n"
"    const int kv_len,\n"
"    const int head_dim\n"
") {\n"
"    const int q_pos = get_global_id(0);\n"
"    const int d = get_global_id(1);\n"
"    const int bh = get_global_id(2);\n"
"    \n"
"    if (q_pos >= seq_len || d >= head_dim) return;\n"
"    \n"
"    const int b = bh / heads;\n"
"    const int h = bh % heads;\n"
"    \n"
"    float sum = 0.0f;\n"
"    int score_base = (bh * seq_len + q_pos) * kv_len;\n"
"    \n"
"    for (int k = 0; k < kv_len; k++) {\n"
"        float score = scores[score_base + k];\n"
"        int v_idx = ((b * heads + h) * kv_len + k) * head_dim + d;\n"
"        sum += score * V[v_idx];\n"
"    }\n"
"    \n"
"    int out_idx = ((b * heads + h) * seq_len + q_pos) * head_dim + d;\n"
"    output[out_idx] = sum;\n"
"}\n"
"\n"

// ============================================================================
// Normalization Kernels
// ============================================================================
"// RMS Normalization\n"
"__kernel void rmsnorm(\n"
"    __global const float* input,\n"
"    __global const float* weight,\n"
"    __global float* output,\n"
"    const int batch,\n"
"    const int hidden_size,\n"
"    const float eps\n"
") {\n"
"    const int local_id = get_local_id(0);\n"
"    const int group_id = get_group_id(0);\n"
"    const int local_size = get_local_size(0);\n"
"    \n"
"    if (group_id >= batch) return;\n"
"    \n"
"    __local float shared[REDUCTION_BLOCK];\n"
"    \n"
"    // Compute sum of squares\n"
"    float sum_sq = 0.0f;\n"
"    for (int i = local_id; i < hidden_size; i += local_size) {\n"
"        float val = input[group_id * hidden_size + i];\n"
"        sum_sq += val * val;\n"
"    }\n"
"    \n"
"    shared[local_id] = sum_sq;\n"
"    barrier(CLK_LOCAL_MEM_FENCE);\n"
"    \n"
"    // Parallel reduction\n"
"    for (int stride = local_size / 2; stride > 0; stride >>= 1) {\n"
"        if (local_id < stride) {\n"
"            shared[local_id] += shared[local_id + stride];\n"
"        }\n"
"        barrier(CLK_LOCAL_MEM_FENCE);\n"
"    }\n"
"    \n"
"    // Compute RMS\n"
"    float rms = rsqrt(shared[0] / hidden_size + eps);\n"
"    \n"
"    // Apply normalization and weight\n"
"    for (int i = local_id; i < hidden_size; i += local_size) {\n"
"        float val = input[group_id * hidden_size + i];\n"
"        output[group_id * hidden_size + i] = val * rms * weight[i];\n"
"    }\n"
"}\n"
"\n"

"// Layer Normalization\n"
"__kernel void layernorm(\n"
"    __global const float* input,\n"
"    __global const float* weight,\n"
"    __global const float* bias,\n"
"    __global float* output,\n"
"    const int batch,\n"
"    const int hidden_size,\n"
"    const float eps\n"
") {\n"
"    const int local_id = get_local_id(0);\n"
"    const int group_id = get_group_id(0);\n"
"    const int local_size = get_local_size(0);\n"
"    \n"
"    if (group_id >= batch) return;\n"
"    \n"
"    __local float shared_sum[REDUCTION_BLOCK];\n"
"    __local float shared_sq[REDUCTION_BLOCK];\n"
"    \n"
"    // Compute sum and sum of squares\n"
"    float sum = 0.0f;\n"
"    float sum_sq = 0.0f;\n"
"    for (int i = local_id; i < hidden_size; i += local_size) {\n"
"        float val = input[group_id * hidden_size + i];\n"
"        sum += val;\n"
"        sum_sq += val * val;\n"
"    }\n"
"    \n"
"    shared_sum[local_id] = sum;\n"
"    shared_sq[local_id] = sum_sq;\n"
"    barrier(CLK_LOCAL_MEM_FENCE);\n"
"    \n"
"    // Parallel reduction\n"
"    for (int stride = local_size / 2; stride > 0; stride >>= 1) {\n"
"        if (local_id < stride) {\n"
"            shared_sum[local_id] += shared_sum[local_id + stride];\n"
"            shared_sq[local_id] += shared_sq[local_id + stride];\n"
"        }\n"
"        barrier(CLK_LOCAL_MEM_FENCE);\n"
"    }\n"
"    \n"
"    // Compute mean and variance\n"
"    float mean = shared_sum[0] / hidden_size;\n"
"    float var = shared_sq[0] / hidden_size - mean * mean;\n"
"    float inv_std = rsqrt(var + eps);\n"
"    \n"
"    // Apply normalization, weight, and bias\n"
"    for (int i = local_id; i < hidden_size; i += local_size) {\n"
"        float val = input[group_id * hidden_size + i];\n"
"        float normalized = (val - mean) * inv_std;\n"
"        float result = normalized * weight[i];\n"
"        if (bias) result += bias[i];\n"
"        output[group_id * hidden_size + i] = result;\n"
"    }\n"
"}\n"
"\n"

// ============================================================================
// Activation Kernels
// ============================================================================
"// SiLU activation: x * sigmoid(x)\n"
"__kernel void silu(\n"
"    __global const float* input,\n"
"    __global float* output,\n"
"    const int n\n"
") {\n"
"    const int idx = get_global_id(0);\n"
"    if (idx >= n) return;\n"
"    \n"
"    float x = input[idx];\n"
"    float sigmoid_x = 1.0f / (1.0f + exp(-x));\n"
"    output[idx] = x * sigmoid_x;\n"
"}\n"
"\n"

"// GELU activation (approximate)\n"
"__kernel void gelu(\n"
"    __global const float* input,\n"
"    __global float* output,\n"
"    const int n\n"
") {\n"
"    const int idx = get_global_id(0);\n"
"    if (idx >= n) return;\n"
"    \n"
"    float x = input[idx];\n"
"    // Approximate GELU: 0.5 * x * (1 + tanh(sqrt(2/pi) * (x + 0.044715 * x^3)))\n"
"    const float SQRT_2_PI = 0.7978845608f;\n"
"    float x3 = x * x * x;\n"
"    float inner = SQRT_2_PI * (x + 0.044715f * x3);\n"
"    output[idx] = 0.5f * x * (1.0f + tanh(inner));\n"
"}\n"
"\n"

// ============================================================================
// RoPE Kernels
// ============================================================================
"// Rotary Position Embedding (1D)\n"
"__kernel void rope(\n"
"    __global const float* x,\n"
"    __global const float* cos_freq,\n"
"    __global const float* sin_freq,\n"
"    __global float* output,\n"
"    const int batch,\n"
"    const int seq_len,\n"
"    const int heads,\n"
"    const int head_dim\n"
") {\n"
"    const int d2 = get_global_id(0);  // head_dim / 2\n"
"    const int pos = get_global_id(1);\n"
"    const int bh = get_global_id(2);\n"
"    \n"
"    if (d2 >= head_dim / 2 || pos >= seq_len) return;\n"
"    \n"
"    const int b = bh / heads;\n"
"    const int h = bh % heads;\n"
"    \n"
"    int base_idx = ((b * heads + h) * seq_len + pos) * head_dim;\n"
"    int d0 = d2 * 2;\n"
"    int d1 = d2 * 2 + 1;\n"
"    \n"
"    float x0 = x[base_idx + d0];\n"
"    float x1 = x[base_idx + d1];\n"
"    \n"
"    float cos_val = cos_freq[pos * (head_dim / 2) + d2];\n"
"    float sin_val = sin_freq[pos * (head_dim / 2) + d2];\n"
"    \n"
"    output[base_idx + d0] = x0 * cos_val - x1 * sin_val;\n"
"    output[base_idx + d1] = x0 * sin_val + x1 * cos_val;\n"
"}\n"
"\n"

"// 2D Rotary Position Embedding (for vision, Qwen2-VL style)\n"
"__kernel void rope_2d(\n"
"    __global const float* x,\n"
"    __global const float* cos_h,\n"
"    __global const float* sin_h,\n"
"    __global const float* cos_w,\n"
"    __global const float* sin_w,\n"
"    __global float* output,\n"
"    const int batch,\n"
"    const int height,\n"
"    const int width,\n"
"    const int heads,\n"
"    const int head_dim\n"
") {\n"
"    const int w = get_global_id(0);\n"
"    const int h = get_global_id(1);\n"
"    const int bh = get_global_id(2);\n"
"    \n"
"    if (w >= width || h >= height) return;\n"
"    \n"
"    const int b = bh / heads;\n"
"    const int head = bh % heads;\n"
"    const int seq_pos = h * width + w;\n"
"    \n"
"    int base_idx = ((b * heads + head) * (height * width) + seq_pos) * head_dim;\n"
"    int half_dim = head_dim / 2;\n"
"    int quarter_dim = head_dim / 4;\n"
"    \n"
"    // Apply height RoPE to first half\n"
"    for (int d = 0; d < quarter_dim; d++) {\n"
"        int d0 = d * 2;\n"
"        int d1 = d * 2 + 1;\n"
"        \n"
"        float x0 = x[base_idx + d0];\n"
"        float x1 = x[base_idx + d1];\n"
"        \n"
"        float cos_val = cos_h[h * quarter_dim + d];\n"
"        float sin_val = sin_h[h * quarter_dim + d];\n"
"        \n"
"        output[base_idx + d0] = x0 * cos_val - x1 * sin_val;\n"
"        output[base_idx + d1] = x0 * sin_val + x1 * cos_val;\n"
"    }\n"
"    \n"
"    // Apply width RoPE to second half\n"
"    for (int d = 0; d < quarter_dim; d++) {\n"
"        int d0 = half_dim + d * 2;\n"
"        int d1 = half_dim + d * 2 + 1;\n"
"        \n"
"        float x0 = x[base_idx + d0];\n"
"        float x1 = x[base_idx + d1];\n"
"        \n"
"        float cos_val = cos_w[w * quarter_dim + d];\n"
"        float sin_val = sin_w[w * quarter_dim + d];\n"
"        \n"
"        output[base_idx + d0] = x0 * cos_val - x1 * sin_val;\n"
"        output[base_idx + d1] = x0 * sin_val + x1 * cos_val;\n"
"    }\n"
"}\n"
"\n"

// ============================================================================
// Element-wise Kernels
// ============================================================================
"// Vector addition: c = a + b\n"
"__kernel void vec_add(\n"
"    __global const float* a,\n"
"    __global const float* b,\n"
"    __global float* c,\n"
"    const int n\n"
") {\n"
"    const int idx = get_global_id(0);\n"
"    if (idx >= n) return;\n"
"    c[idx] = a[idx] + b[idx];\n"
"}\n"
"\n"

"// Vector multiplication: c = a * b\n"
"__kernel void vec_mul(\n"
"    __global const float* a,\n"
"    __global const float* b,\n"
"    __global float* c,\n"
"    const int n\n"
") {\n"
"    const int idx = get_global_id(0);\n"
"    if (idx >= n) return;\n"
"    c[idx] = a[idx] * b[idx];\n"
"}\n"
"\n"

"// Vector scale: y = x * scale\n"
"__kernel void vec_scale(\n"
"    __global const float* x,\n"
"    __global float* y,\n"
"    const float scale,\n"
"    const int n\n"
") {\n"
"    const int idx = get_global_id(0);\n"
"    if (idx >= n) return;\n"
"    y[idx] = x[idx] * scale;\n"
"}\n"
"\n"

// ============================================================================
// Dequantization Kernels
// ============================================================================
"// Dequantize Q8_0 to float32\n"
"__kernel void dequant_q8(\n"
"    __global const char* input,\n"
"    __global const float* scales,\n"
"    __global float* output,\n"
"    const int n\n"
") {\n"
"    const int idx = get_global_id(0);\n"
"    if (idx >= n) return;\n"
"    \n"
"    int block_idx = idx / DEQUANT_BLOCK;\n"
"    float scale = scales[block_idx];\n"
"    output[idx] = (float)input[idx] * scale;\n"
"}\n"
"\n"

"// Dequantize Q4_0 to float32 (packed 2 values per byte)\n"
"__kernel void dequant_q4(\n"
"    __global const uchar* input,\n"
"    __global const float* scales,\n"
"    __global float* output,\n"
"    const int n\n"
") {\n"
"    const int idx = get_global_id(0);\n"
"    if (idx >= n) return;\n"
"    \n"
"    int block_idx = idx / DEQUANT_BLOCK;\n"
"    float scale = scales[block_idx];\n"
"    \n"
"    int byte_idx = idx / 2;\n"
"    uchar packed = input[byte_idx];\n"
"    \n"
"    int val;\n"
"    if (idx % 2 == 0) {\n"
"        val = (int)(packed & 0x0F) - 8;\n"
"    } else {\n"
"        val = (int)(packed >> 4) - 8;\n"
"    }\n"
"    \n"
"    output[idx] = (float)val * scale;\n"
"}\n"
;

#endif // OPENCL_KERNELS_H

